package de.igbdsandzakkassel.vaktija.data.community

import de.igbdsandzakkassel.vaktija.data.model.Community
import de.igbdsandzakkassel.vaktija.data.model.CommunityLocation
import de.igbdsandzakkassel.vaktija.data.model.CommunityRules
import java.time.LocalTime

/**
 * GENERATED by tools/gen_seed.py from docs/multi-gemeinde/communities.json — do not edit by hand.
 *
 * The list the app offers when Firestore has nothing to say. The real catalogue lives in Firestore
 * on purpose: communities pay to be listed, so adding one must never mean shipping an app update
 * and waiting for Play review. Anything Firestore returns replaces this entirely.
 */
object CommunityCatalog {

    const val KASSEL_ID = "igbd-gemeinde-sandzak-kassel"

    val SEED: List<Community> = listOf(
        Community(
            id = "bosniakisch-deutsche-gemeinde-karlsruhe-e-v",
            name = "Bosniakisch-Deutsche Gemeinde Karlsruhe e.V.",
            address = "Pfalzbahnstraße 4, 76187 Karlsruhe",
            locations = listOf(
                CommunityLocation(
                    id = "karlsruhe",
                    name = "Karlsruhe",
                    vaktijaSlug = "karlsruhe",
                    latitude = 49.026653,
                    longitude = 8.341525,
                ),
            ),
        ),
        Community(
            id = "dzemat-essen-e-v",
            name = "Džemat Essen e.V.",
            address = "Rahmstraße 253, 45326 Essen",
            locations = listOf(
                CommunityLocation(
                    id = "essen",
                    name = "Essen",
                    vaktijaSlug = "essen",
                    latitude = 51.496402,
                    longitude = 7.018705,
                ),
            ),
        ),
        Community(
            id = "dzemat-ikre-berlin-e-v",
            name = "Džemat IKRE Berlin e.V.",
            address = "Ollenhauerstraße 15, 13403 Berlin",
            locations = listOf(
                CommunityLocation(
                    id = "berlin",
                    name = "Berlin",
                    vaktijaSlug = "berlin",
                    latitude = 52.566752,
                    longitude = 13.329335,
                ),
            ),
        ),
        Community(
            id = "gemeinde-bosnischer-moslems-e-v-dzemat-bremen",
            name = "Gemeinde bosnischer Moslems e.V. — Džemat Bremen",
            address = "Schiffbauerweg 4, 28237 Bremen",
            locations = listOf(
                CommunityLocation(
                    id = "bremen",
                    name = "Bremen",
                    vaktijaSlug = "bremen",
                    latitude = 53.113772,
                    longitude = 8.750703,
                ),
            ),
        ),
        Community(
            id = "dzemat-bkc-siegen-e-v",
            name = "IGBD-Džemat BKC Siegen e.V.",
            address = "Obere Kaiserstraße 6, 57078 Siegen",
            locations = listOf(
                CommunityLocation(
                    id = "siegen",
                    name = "Siegen",
                    vaktijaSlug = "siegen",
                    latitude = 50.918402,
                    longitude = 8.014279,
                ),
            ),
        ),
        Community(
            id = "boeblingen-sindelfingen-e-v",
            name = "IGBD-Gemeinde Böblingen/Sindelfingen e.V.",
            address = "Max-Eyth-Straße 4, 71065 Sindelfingen",
            locations = listOf(
                CommunityLocation(
                    id = "sindelfingen",
                    name = "Sindelfingen",
                    vaktijaSlug = "sindelfingen",
                    latitude = 48.697492,
                    longitude = 9.005919,
                ),
            ),
        ),
        Community(
            id = "duisburg-e-v",
            name = "IGBD-Gemeinde Duisburg e.V.",
            address = "Ziethenstraße 49, 47169 Duisburg",
            locations = listOf(
                CommunityLocation(
                    id = "duisburg",
                    name = "Duisburg",
                    vaktijaSlug = "duisburg",
                    latitude = 51.514294,
                    longitude = 6.758057,
                ),
            ),
        ),
        Community(
            id = "hagen-e-v",
            name = "IGBD-Gemeinde Hagen e.V.",
            address = "Augustastraße 22, 58089 Hagen",
            locations = listOf(
                CommunityLocation(
                    id = "hagen",
                    name = "Hagen",
                    vaktijaSlug = "hagen",
                    latitude = 51.357705,
                    longitude = 7.460284,
                ),
            ),
        ),
        Community(
            id = "hannover-e-v",
            name = "IGBD-Gemeinde Hannover e.V.",
            address = "Varrelheidering 4, 30659 Hannover",
            locations = listOf(
                CommunityLocation(
                    id = "hannover",
                    name = "Hannover",
                    vaktijaSlug = "hannover",
                    latitude = 52.425764,
                    longitude = 9.826992,
                ),
            ),
        ),
        Community(
            id = "mainz-e-v",
            name = "IGBD-Gemeinde Mainz e.V.",
            address = "Curiestraße 15a, 55129 Mainz",
            locations = listOf(
                CommunityLocation(
                    id = "mainz",
                    name = "Mainz",
                    vaktijaSlug = "mainz",
                    latitude = 49.970457,
                    longitude = 8.266303,
                ),
            ),
        ),
        Community(
            id = "mannheim-e-v",
            name = "IGBD-Gemeinde Mannheim e.V.",
            address = "Neonstraße 5, 68199 Mannheim",
            locations = listOf(
                CommunityLocation(
                    id = "mannheim",
                    name = "Mannheim",
                    vaktijaSlug = "mannheim",
                    latitude = 49.460997,
                    longitude = 8.494575,
                ),
            ),
        ),
        Community(
            id = "nuernberg-e-v",
            name = "IGBD-Gemeinde Nürnberg e.V.",
            address = "Turnerheimstraße 48, 90441 Nürnberg",
            locations = listOf(
                CommunityLocation(
                    id = "nuernberg",
                    name = "Nürnberg",
                    vaktijaSlug = "nuernberg",
                    latitude = 49.428317,
                    longitude = 11.045981,
                ),
            ),
        ),
        Community(
            id = "oberhausen-e-v",
            name = "IGBD-Gemeinde Oberhausen e.V.",
            address = "Fahnhorststraße 32, 46117 Oberhausen",
            locations = listOf(
                CommunityLocation(
                    id = "oberhausen",
                    name = "Oberhausen",
                    vaktijaSlug = "oberhausen",
                    latitude = 51.501748,
                    longitude = 6.870051,
                ),
            ),
        ),
        Community(
            id = "offenburg-e-v",
            name = "IGBD-Gemeinde Offenburg e.V.",
            address = "Okenstraße 73, 77652 Offenburg",
            locations = listOf(
                CommunityLocation(
                    id = "hohberg",
                    name = "Höhberg",
                    vaktijaSlug = "hohberg",
                    latitude = 48.480668,
                    longitude = 7.945542,
                ),
            ),
        ),
        Community(
            id = "rosenheim-e-v",
            name = "IGBD-Gemeinde Rosenheim e.V.",
            address = "Burgfriedstraße 55, 83024 Rosenheim",
            locations = listOf(
                CommunityLocation(
                    id = "rosenheim",
                    name = "Rosenheim",
                    vaktijaSlug = "rosenheim",
                    latitude = 47.866545,
                    longitude = 12.113048,
                ),
            ),
        ),
        Community(
            id = "igbd-gemeinde-sandzak-kassel",
            name = "IGBD-Gemeinde Sandžak-Kassel",
            address = "Schwanenweg 13, 34123 Kassel",
            email = "vorstand@igbdsandzakkassel.de",
            donationUrl = "https://www.paypal.com/donate?business=ikzsandzakkassel@gmail.com",
            locations = listOf(
                CommunityLocation(
                    id = "kassel",
                    name = "Kassel",
                    vaktijaSlug = "kassel",
                    latitude = 51.3093,
                    longitude = 9.5132,
                ),
                CommunityLocation(
                    id = "hann-muenden",
                    name = "Hann. Münden",
                    vaktijaSlug = "hann-munden",
                    latitude = 51.4194,
                    longitude = 9.6524,
                ),
                CommunityLocation(
                    id = "korbach",
                    name = "Korbach",
                    vaktijaSlug = "brilon",
                    latitude = 51.2761,
                    longitude = 8.8735,
                ),
                CommunityLocation(
                    id = "beverungen",
                    name = "Beverungen",
                    vaktijaSlug = "beverungen",
                    latitude = 51.6667,
                    longitude = 9.3667,
                ),
                CommunityLocation(
                    id = "melsungen",
                    name = "Melsungen",
                    vaktijaSlug = "knullwald",
                    latitude = 51.1333,
                    longitude = 9.55,
                ),
            ),
        ),
        Community(
            id = "ulm-e-v",
            name = "IGBD-Gemeinde Ulm e.V.",
            address = "Auchertwiesenweg 21, 89081 Ulm",
            locations = listOf(
                CommunityLocation(
                    id = "ulm",
                    name = "Ulm",
                    vaktijaSlug = "ulm",
                    latitude = 48.400763,
                    longitude = 9.951982,
                ),
            ),
        ),
        Community(
            id = "witten-e-v",
            name = "IGBD-Gemeinde Witten e.V.",
            address = "Breite Straße 5, 58452 Witten",
            locations = listOf(
                CommunityLocation(
                    id = "witten",
                    name = "Witten",
                    vaktijaSlug = "witten",
                    latitude = 51.438767,
                    longitude = 7.329269,
                ),
            ),
        ),
        Community(
            id = "wuppertal-e-v",
            name = "IGBD-Gemeinde Wuppertal e.V.",
            address = "Uellendahler Straße 6A, 42107 Wuppertal",
            locations = listOf(
                CommunityLocation(
                    id = "wuppertal",
                    name = "Wuppertal",
                    vaktijaSlug = "wuppertal",
                    latitude = 51.269046,
                    longitude = 7.148558,
                ),
            ),
        ),
        Community(
            id = "islamische-gemeinschaft-bih-aachen",
            name = "Islamische Gemeinschaft „BiH\" Aachen",
            address = "Josefstraße 158, 52080 Aachen",
            locations = listOf(
                CommunityLocation(
                    id = "aachen",
                    name = "Aachen",
                    vaktijaSlug = "aachen",
                    latitude = 50.784228,
                    longitude = 6.154374,
                ),
            ),
        ),
    )

    /**
     * The Iqamah and Jumu'ah each community starts with, written once when the catalogue is
     * imported. From then on they live in `communities/{id}/config/rules`, edited by that
     * community's own admin — they change through the year and must never need an app release.
     *
     * Seeded per community rather than left to one shared default: a community whose Jumu'ah was
     * announced as Kassel's 15:00 would send its people to an empty prayer hall.
     */
    val SEED_RULES: Map<String, CommunityRules> = mapOf(
        "bosniakisch-deutsche-gemeinde-karlsruhe-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "dzemat-essen-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "dzemat-ikre-berlin-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "gemeinde-bosnischer-moslems-e-v-dzemat-bremen" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "dzemat-bkc-siegen-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "boeblingen-sindelfingen-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "duisburg-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "hagen-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "hannover-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "mainz-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "mannheim-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "nuernberg-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "oberhausen-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "offenburg-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "rosenheim-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "igbd-gemeinde-sandzak-kassel" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "ulm-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "witten-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "wuppertal-e-v" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
        "islamische-gemeinschaft-bih-aachen" to CommunityRules(
            fajrIqamah = LocalTime.parse("05:15"),
            jumua = LocalTime.parse("15:00"),
            dhuhrOffsetMin = 10,
            asrOffsetMin = 10,
            maghribOffsetMin = 5,
            ishaOffsetMin = 0,
        ),
    )

    /** The location a pre-multi-community install is silently migrated onto. */
    val DEFAULT_LOCATION_ID: String =
        SEED.firstOrNull { it.id == KASSEL_ID }?.locations?.firstOrNull()?.id ?: "kassel"
}
