"""Generate CommunityCatalog.kt from docs/multi-gemeinde/communities.json.

The bundled catalogue is a FALLBACK: the moment Firestore holds communities, that wins. It exists
so a first launch with no network is not an empty picker — and, right now, so the app can be tried
before Firestore is populated at all.

Generated rather than hand-written so the JSON stays the single source of truth: the file the
communities' details are collected into is the same one the app falls back to.

Run:  python tools/gen_seed.py
"""

import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "multi-gemeinde", "communities.json")
OUT = os.path.join(ROOT, "app", "src", "main", "java", "de", "igbdsandzakkassel",
                   "vaktija", "data", "community", "CommunityCatalog.kt")

KASSEL_ID = "igbd-gemeinde-sandzak-kassel"


def kt(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\$") + '"'


def render(c):
    lines = [f"        Community("]
    lines.append(f"            id = {kt(c['id'])},")
    lines.append(f"            name = {kt(c['name'])},")
    if c.get("address"):
        lines.append(f"            address = {kt(c['address'])},")
    if c.get("email"):
        lines.append(f"            email = {kt(c['email'])},")
    if c.get("donationUrl"):
        lines.append(f"            donationUrl = {kt(c['donationUrl'])},")
    if c.get("logoUrl"):
        lines.append(f"            logoUrl = {kt(c['logoUrl'])},")
    lines.append("            locations = listOf(")
    for loc in c["locations"]:
        lines.append("                CommunityLocation(")
        lines.append(f"                    id = {kt(loc['id'])},")
        lines.append(f"                    name = {kt(loc['name'])},")
        lines.append(f"                    vaktijaSlug = {kt(loc['vaktijaSlug'])},")
        lines.append(f"                    latitude = {loc['latitude']},")
        lines.append(f"                    longitude = {loc['longitude']},")
        lines.append("                ),")
    lines.append("            ),")
    lines.append("        ),")
    return "\n".join(lines)


def main():
    data = json.load(io.open(SRC, encoding="utf-8"))
    data.sort(key=lambda c: c["name"].lower())
    body = "\n".join(render(c) for c in data)
    src = f'''package de.igbdsandzakkassel.vaktija.data.community

import de.igbdsandzakkassel.vaktija.data.model.Community
import de.igbdsandzakkassel.vaktija.data.model.CommunityLocation

/**
 * GENERATED by tools/gen_seed.py from docs/multi-gemeinde/communities.json — do not edit by hand.
 *
 * The list the app offers when Firestore has nothing to say. The real catalogue lives in Firestore
 * on purpose: communities pay to be listed, so adding one must never mean shipping an app update
 * and waiting for Play review. Anything Firestore returns replaces this entirely.
 *
 * Iqamah and Jumu'ah times are NOT here — those live in the community's Firestore document, because
 * they change through the year and an admin has to be able to edit them without a release.
 */
object CommunityCatalog {{

    const val KASSEL_ID = {kt(KASSEL_ID)}

    val SEED: List<Community> = listOf(
{body}
    )

    /** The location a pre-multi-community install is silently migrated onto. */
    val DEFAULT_LOCATION_ID: String =
        SEED.firstOrNull {{ it.id == KASSEL_ID }}?.locations?.firstOrNull()?.id ?: "kassel"
}}
'''
    io.open(OUT, "w", encoding="utf-8").write(src)
    print(f"{len(data)} Gemeinden -> {os.path.relpath(OUT, ROOT)}")


if __name__ == "__main__":
    main()
