"""Generate CommunityCatalog.kt from docs/multi-gemeinde/communities.json.

The bundled catalogue is a FALLBACK: the moment Firestore holds communities, that wins. It exists
so a first launch with no network is not an empty picker — and, right now, so the app can be tried
before Firestore is populated at all.

Generated rather than hand-written so the JSON stays the single source of truth: the file the
communities' details are collected into is the same one the app falls back to.

Run:  python tools/gen_seed.py
"""

import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "docs", "multi-gemeinde", "communities.json")
OUT = os.path.join(ROOT, "app", "src", "main", "java", "de", "igbdsandzakkassel",
                   "vaktija", "data", "community", "CommunityCatalog.kt")

KASSEL_ID = "igbd-gemeinde-sandzak-kassel"


def kt(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$") + '"'


def render(c):
    lines = ["        Community("]
    lines.append("            id = %s," % kt(c["id"]))
    lines.append("            name = %s," % kt(c["name"]))
    if c.get("address"):
        lines.append("            address = %s," % kt(c["address"]))
    if c.get("email"):
        lines.append("            email = %s," % kt(c["email"]))
    if c.get("donationUrl"):
        lines.append("            donationUrl = %s," % kt(c["donationUrl"]))
    if c.get("logoUrl"):
        lines.append("            logoUrl = %s," % kt(c["logoUrl"]))
    lines.append("            locations = listOf(")
    for loc in c["locations"]:
        lines.append("                CommunityLocation(")
        lines.append("                    id = %s," % kt(loc["id"]))
        lines.append("                    name = %s," % kt(loc["name"]))
        lines.append("                    vaktijaSlug = %s," % kt(loc["vaktijaSlug"]))
        lines.append("                    latitude = %s," % loc["latitude"])
        lines.append("                    longitude = %s," % loc["longitude"])
        lines.append("                ),")
    lines.append("            ),")
    lines.append("        ),")
    return "\n".join(lines)


def render_rules(c):
    """The Iqamah and Jumu'ah a community starts with, written once at import."""
    lines = ["        %s to CommunityRules(" % kt(c["id"])]
    lines.append("            fajrIqamah = LocalTime.parse(%s)," % kt(c["fajrIqamah"]))
    lines.append("            jumua = LocalTime.parse(%s)," % kt(c["jumua"]))
    lines.append("            dhuhrOffsetMin = %s," % c["dhuhrOffsetMin"])
    lines.append("            asrOffsetMin = %s," % c["asrOffsetMin"])
    lines.append("            maghribOffsetMin = %s," % c["maghribOffsetMin"])
    lines.append("            ishaOffsetMin = %s," % c["ishaOffsetMin"])
    lines.append("        ),")
    return "\n".join(lines)


TEMPLATE = '''package de.igbdsandzakkassel.vaktija.data.community

import de.igbdsandzakkassel.vaktija.data.model.Community
import de.igbdsandzakkassel.vaktija.data.model.CommunityLocation
import de.igbdsandzakkassel.vaktija.data.model.CommunityRules
import java.time.LocalTime

/**
 * GENERATED by tools/gen_seed.py from docs/multi-gemeinde/communities.json — do not edit by hand.
 *
 * The list the app offers when Firestore has nothing to say. The real catalogue lives in Firestore
 * on purpose: communities pay to be listed, so adding one must never mean shipping an app update
 * and waiting for Play review. Anything Firestore returns replaces this entirely.
 */
object CommunityCatalog {

    const val KASSEL_ID = %(kassel)s

    val SEED: List<Community> = listOf(
%(body)s
    )

    /**
     * The Iqamah and Jumu'ah each community starts with, written once when the catalogue is
     * imported. From then on they live in `communities/{id}/config/rules`, edited by that
     * community's own admin — they change through the year and must never need an app release.
     *
     * Seeded per community rather than left to one shared default: a community whose Jumu'ah was
     * announced as Kassel's 15:00 would send its people to an empty prayer hall.
     */
    val SEED_RULES: Map<String, CommunityRules> = mapOf(
%(rules)s
    )

    /** The location a pre-multi-community install is silently migrated onto. */
    val DEFAULT_LOCATION_ID: String =
        SEED.firstOrNull { it.id == KASSEL_ID }?.locations?.firstOrNull()?.id ?: "kassel"
}
'''


def main():
    data = json.load(io.open(SRC, encoding="utf-8"))
    data.sort(key=lambda c: c["name"].lower())
    src = TEMPLATE % {
        "kassel": kt(KASSEL_ID),
        "body": "\n".join(render(c) for c in data),
        "rules": "\n".join(render_rules(c) for c in data),
    }
    io.open(OUT, "w", encoding="utf-8").write(src)
    print("%d Gemeinden -> %s" % (len(data), os.path.relpath(OUT, ROOT)))


if __name__ == "__main__":
    main()
